import { Application, Project, Supporter, TriageResult } from './types';

export const mockApplications: Application[] = [
  {
    id: 'app-001',
    applicantId: 'user-001',
    title: 'Renewable Energy Training Academy',
    description: 'A comprehensive training program for renewable energy technicians in rural Romania',
    stream: 'A',
    status: 'in-pilot',
    triageStatus: 'eligible',
    submittedAt: new Date('2024-09-15'),
    scores: {
      feasibility: 35,
      scalability: 28,
      innovation: 18,
      alignment: 9,
    },
    totalScore: 90,
    strategicObjective: 'Climate Action',
    ecosystemLever: 'Education',
    chapterFit: 'Transylvania Region',
    attachments: ['pitch-deck.pdf', 'financial-model.xlsx'],
  },
  {
    id: 'app-002',
    applicantId: 'user-002',
    title: 'Circular Economy Marketplace MVP',
    description: 'A digital platform connecting local artisans with sustainable consumers',
    stream: 'B',
    status: 'shortlisted',
    triageStatus: 'eligible',
    submittedAt: new Date('2024-10-01'),
    scores: {
      feasibility: 32,
      scalability: 25,
      innovation: 19,
      alignment: 8,
    },
    totalScore: 84,
    strategicObjective: 'Economic Development',
    ecosystemLever: 'Market Access',
    chapterFit: 'Bucharest Metro',
    attachments: ['prototype-demo.mp4', 'user-research.pdf'],
  },
  {
    id: 'app-003',
    applicantId: 'user-003',
    title: 'Rural Water Systems Upgrade',
    description: 'Installing and maintaining clean water infrastructure in underserved villages',
    stream: 'A',
    status: 'ai-revision',
    triageStatus: 'needs-revision',
    submittedAt: new Date('2024-11-05'),
    scores: {
      feasibility: 28,
      scalability: 18,
      innovation: 12,
      alignment: 9,
    },
    totalScore: 67,
    riskFlags: ['Limited technical capacity', 'Sustainability unclear'],
    attachments: ['budget-estimate.pdf'],
  },
  {
    id: 'app-004',
    applicantId: 'user-004',
    title: 'Youth Tech Skills Program',
    description: 'Free coding bootcamp for disadvantaged youth',
    stream: 'B',
    status: 'submitted',
    triageStatus: 'eligible',
    submittedAt: new Date('2024-11-20'),
    scores: {
      feasibility: 38,
      scalability: 27,
      innovation: 16,
      alignment: 10,
    },
    totalScore: 91,
    strategicObjective: 'Social Equity',
    ecosystemLever: 'Skills Development',
    chapterFit: 'Cluj-Napoca',
    attachments: ['curriculum.pdf', 'partner-letters.pdf'],
  },
  {
    id: 'app-005',
    applicantId: 'user-005',
    title: 'Agricultural Cooperative Network',
    description: 'Connecting small farmers for collective bargaining and sustainability practices',
    stream: 'A',
    status: 'ai-eligible',
    triageStatus: 'eligible',
    submittedAt: new Date('2024-12-01'),
    scores: {
      feasibility: 33,
      scalability: 29,
      innovation: 17,
      alignment: 9,
    },
    totalScore: 88,
    strategicObjective: 'Rural Development',
    ecosystemLever: 'Cooperative Models',
    attachments: ['feasibility-study.pdf'],
  },
];

export const mockProjects: Project[] = [
  {
    id: 'proj-001',
    applicationId: 'app-001',
    title: 'Renewable Energy Training Academy',
    description: 'A comprehensive training program for renewable energy technicians in rural Romania',
    status: 'pilot',
    stage: 'chapter-pilot',
    teamLead: 'user-001',
    budget: 150000,
    startDate: new Date('2024-06-01'),
    targetOutcome: 'Train 500 technicians annually',
    milestones: [
      {
        id: 'ms-001',
        title: 'Curriculum Development',
        description: 'Complete curriculum for 6-month program',
        status: 'completed',
        dueDate: new Date('2024-07-31'),
        owner: 'user-001',
      },
      {
        id: 'ms-002',
        title: 'First Cohort Launch',
        description: 'Launch first pilot cohort in Transylvania',
        status: 'in-progress',
        dueDate: new Date('2024-12-31'),
        owner: 'user-001',
      },
      {
        id: 'ms-003',
        title: 'Graduate Job Placement',
        description: '80% job placement rate within 3 months',
        status: 'backlog',
        dueDate: new Date('2025-06-30'),
      },
    ],
    chapters: [
      {
        id: 'ch-001',
        name: 'Transylvania Regional Hub',
        region: 'Transylvania',
        pilotStart: new Date('2024-09-01'),
        capacity: 50,
        available: true,
      },
    ],
    supporterRequests: [
      {
        id: 'sr-001',
        projectId: 'proj-001',
        type: 'expertise',
        description: 'Technical instructors with renewable energy background',
        status: 'pending',
      },
      {
        id: 'sr-002',
        projectId: 'proj-001',
        type: 'network',
        description: 'Job placement partnerships with energy companies',
        status: 'open',
      },
    ],
    impactData: {
      beneficiaries: 150,
      outcomes: [
        {
          metric: 'Technicians Trained',
          target: 500,
          current: 150,
          unit: 'people',
        },
        {
          metric: 'Job Placement Rate',
          target: 80,
          current: 75,
          unit: '%',
        },
      ],
      outputs: [
        {
          metric: 'Training Hours Delivered',
          target: 3000,
          current: 2100,
          unit: 'hours',
        },
      ],
      costPerOutcome: 1000,
      satisfaction: 88,
      ragStatus: 'green',
    },
    nextReviewDate: new Date('2025-03-01'),
  },
  {
    id: 'proj-002',
    applicationId: 'app-002',
    title: 'Circular Economy Marketplace MVP',
    description: 'A digital platform connecting local artisans with sustainable consumers',
    status: 'incubation',
    stage: 'incubation',
    teamLead: 'user-002',
    budget: 75000,
    startDate: new Date('2024-10-15'),
    targetOutcome: 'Connect 200 artisans and 5000 consumers',
    milestones: [
      {
        id: 'ms-201',
        title: 'MVP Launch',
        description: 'Beta launch of marketplace platform',
        status: 'in-progress',
        dueDate: new Date('2025-01-31'),
        owner: 'user-002',
      },
      {
        id: 'ms-202',
        title: 'User Research & Validation',
        description: 'Conduct 50+ user interviews',
        status: 'in-progress',
        dueDate: new Date('2025-02-28'),
      },
      {
        id: 'ms-203',
        title: 'Pilot Market Launch',
        description: 'Launch in Bucharest and Cluj-Napoca',
        status: 'backlog',
        dueDate: new Date('2025-05-31'),
      },
    ],
    chapters: [],
    supporterRequests: [
      {
        id: 'sr-201',
        projectId: 'proj-002',
        type: 'capital',
        amount: 25000,
        description: 'Additional development and marketing budget',
        status: 'open',
      },
      {
        id: 'sr-202',
        projectId: 'proj-002',
        type: 'expertise',
        description: 'E-commerce and platform scaling expertise',
        status: 'open',
      },
    ],
    impactData: {
      outcomes: [
        {
          metric: 'Artisans Connected',
          target: 200,
          current: 45,
          unit: 'people',
        },
        {
          metric: 'Active Consumers',
          target: 5000,
          current: 800,
          unit: 'people',
        },
      ],
      outputs: [
        {
          metric: 'Total Transaction Volume',
          target: 100000,
          current: 12000,
          unit: 'EUR',
        },
      ],
      ragStatus: 'amber',
    },
    nextReviewDate: new Date('2025-02-15'),
  },
];

export const mockSupporters: Supporter[] = [
  {
    id: 'supp-001',
    name: 'Elena Popescu',
    email: 'elena@impact-fund.ro',
    contributionTypes: ['capital', 'expertise'],
    interests: ['Energy', 'Climate', 'Rural Development'],
    region: 'Transylvania',
    availability: '5-10 hours/month',
    pledges: [],
    createdAt: new Date('2024-08-01'),
  },
  {
    id: 'supp-002',
    name: 'Tech Ventures Romania',
    email: 'team@techventures.ro',
    contributionTypes: ['expertise', 'network', 'leadership'],
    interests: ['Technology', 'E-commerce', 'Digital Innovation'],
    region: 'Bucharest Metro',
    availability: 'Flexible',
    pledges: [],
    createdAt: new Date('2024-09-15'),
  },
  {
    id: 'supp-003',
    name: 'Agricultural Cooperative Federation',
    email: 'info@agrifed.ro',
    contributionTypes: ['network', 'leadership'],
    interests: ['Agriculture', 'Rural Development', 'Sustainability'],
    region: 'National',
    pledges: [],
    createdAt: new Date('2024-10-01'),
  },
];

export const mockTriageResults: Record<string, TriageResult> = {
  'app-001': {
    applicationId: 'app-001',
    status: 'eligible',
    suggestedStream: 'A',
    scores: {
      feasibility: 35,
      scalability: 28,
      innovation: 18,
      alignment: 9,
    },
    reasoning: [
      'Clear market need and existing demand from rural communities',
      'Scalable training model that can be replicated across regions',
      'Strong alignment with climate and employment objectives',
      'Experienced team with renewable energy background',
    ],
    missingInfo: [],
  },
  'app-002': {
    applicationId: 'app-002',
    status: 'eligible',
    suggestedStream: 'B',
    scores: {
      feasibility: 32,
      scalability: 25,
      innovation: 19,
      alignment: 8,
    },
    reasoning: [
      'Innovative digital-first approach to sustainable commerce',
      'MVP developed with early user validation',
      'Strong founder commitment and execution plan',
      'Addresses market gap in sustainable consumer access',
    ],
    missingInfo: ['Financial projections beyond Year 1', 'Supply chain sustainability plan'],
  },
  'app-003': {
    applicationId: 'app-003',
    status: 'needs-revision',
    suggestedStream: 'A',
    scores: {
      feasibility: 28,
      scalability: 18,
      innovation: 12,
      alignment: 9,
    },
    reasoning: [
      'Important social challenge but current proposal lacks sustainability planning',
      'Technical capacity assessment incomplete',
      'Cost estimates need detailed breakdown',
    ],
    missingInfo: [
      'Long-term maintenance and cost recovery model',
      'Technical team expertise documentation',
      'Community engagement and contribution plan',
      'Environmental impact assessment',
    ],
  },
};

export const pipelineStatuses = [
  { label: 'Submitted', count: 12, color: 'bg-slate-400' },
  { label: 'AI Eligible', count: 28, color: 'bg-blue-400' },
  { label: 'AI Revision', count: 8, color: 'bg-yellow-400' },
  { label: 'Shortlisted', count: 15, color: 'bg-purple-400' },
  { label: 'Accepted', count: 6, color: 'bg-green-500' },
  { label: 'In Pilot', count: 4, color: 'bg-emerald-500' },
  { label: 'Scaling', count: 2, color: 'bg-teal-500' },
];

export const strategicObjectives = [
  { id: 'so-001', name: 'Climate Action', description: 'Environmental sustainability', active: true },
  { id: 'so-002', name: 'Social Equity', description: 'Fair access and opportunity', active: true },
  { id: 'so-003', name: 'Economic Development', description: 'Inclusive growth', active: true },
  { id: 'so-004', name: 'Rural Development', description: 'Rural community strengthening', active: true },
];

export const ecosystemLevers = [
  { id: 'el-001', name: 'Education', description: 'Skills and knowledge building', active: true },
  { id: 'el-002', name: 'Market Access', description: 'Supply chain and sales channels', active: true },
  { id: 'el-003', name: 'Financing', description: 'Capital and financial services', active: true },
  { id: 'el-004', name: 'Technology', description: 'Digital tools and innovation', active: true },
  { id: 'el-005', name: 'Cooperative Models', description: 'Collective action structures', active: true },
];

export const chapters = [
  {
    id: 'ch-001',
    name: 'Bucharest Metro',
    region: 'Bucharest',
    capacity: 8,
    available: true,
  },
  {
    id: 'ch-002',
    name: 'Cluj-Napoca Hub',
    region: 'Cluj-Napoca',
    capacity: 6,
    available: true,
  },
  {
    id: 'ch-003',
    name: 'Transylvania Regional',
    region: 'Transylvania',
    capacity: 5,
    available: false,
  },
  {
    id: 'ch-004',
    name: 'Moldavia Network',
    region: 'Moldavia',
    capacity: 4,
    available: true,
  },
];
